apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: petclinic-vets
  labels:
    app: petclinic-vets
spec:
  selector:
    matchLabels:
      app: petclinic-vets
  template:
    metadata:
      labels:
        app: petclinic-vets
    spec:
      containers:
      - name: petclinic-vets
        image: soloio/petclinic-vet@sha256:4bf705f28a032b2b3edd00ccaed58a7cb3ea6dedd005eecc2cde8e7a6ae71e70
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http-squash-api
        command: ["/petclinic-vet"]

---
kind: Service
apiVersion: v1
metadata:
  name: petclinic-vets
spec:
  selector:
    app: petclinic-vets
  ports:
    - name: http-petclinic-vets-api
      protocol: TCP
      port: 80
      targetPort: 8080